### ISSUE TITLE
Unable to interact with Blind Map

### ISSUE THREAD

**Issue by ghostwich** [hundredrabbits/Verreciel#15]
The prompt is to route Blind Map to map.  Nothing happens trying to route in either direction.  Cannot proceed in the game.  A reset will resume the game in the Senni Horadric, with the prompt to travel to Ursul system.

**Comment by neauoire** [comment]
Let me test this out :) Thanks for the head's up.
You are on Version 1.2?

**Comment by ghostwich** [comment]
Yes, version 1.2.

My device is an iPhone 5s on iOS 9.3.2 (and 9.3.3 beta).

Thanks!

**Comment by neauoire** [comment]
Is it possible that the fog map is already in your map port?
Is the MAP port cyan or grey?

**Comment by Rezmason** [comment]
Can repro on version 1.4.

Just transferred the Blind Map from the Usual Telescope to my Cargo. The text "Route Blind Map to Map" is onscreen. The Cargo module is routed to the Console, which shows the Blind Map as cyan. In the Battery module, I have a cyan Cell routed to the grey Map port. In the Radar module, the Map port is cyan, but nothing is routed to it.

When I route the Blind Map from the Console module to the Map port on the Radar module, nothing happens.

**Comment by neauoire** [comment]
It's possible that the fog map is in the Map Port. Route the map port to your cargo or to the console and see what is displayed. If it indeed the blind map, let me know and I will investigate further.

**Comment by Rezmason** [comment]
Oh, that worked! The Fog Map was transferred to the Cargo module, and the Map port on the Radar module turned grey. I can put it back, too, and once I do, the words "Fog Map" appear below that port.

I can say with certainty, though, that "Fog Map" wasn't there before. In other words, the ports are behaving in the way we expect them to, but not the map port's label in the Radar module. It seems to be sensitive to when I quit and reopen the app.

**Comment by ghostwich** [comment]
I wanted to report that this does indeed work, but to echo Rezmason: the map does not show that it “contains” the fog map.  The same thing happens to the radio, therefore trying to route map to cargo didn’t even occur to me.

I am pretty sure this is a bug upon loading the game or resuming it from a saved state, where map and radio do not show as having anything “within” them.

**Comment by neauoire** [comment]
Oh! that is a bug!
Let me fix this.

**Comment by neauoire** [comment]
Fixed :)
