### ISSUE TITLE
Routing diamond tap area becomes tiny

### ISSUE THREAD

**Issue by flagoworld** [hundredrabbits/Verreciel#16]
At least i think thats what happens. Every time I dock at least one routing diamond becomes very difficult to press. If i spam tap it for a while it eventually selects and I can route it elsewhere. Makes the game very difficult to play. Other than this issue it is very fun.

**Comment by neauoire** [comment]
This is weird, could you screencap? This is on iPhone 6 right?

**Comment by neauoire** [comment]
Fixed
