### ISSUE TITLE
Recommendation: allow a new incoming wire to disconnect an old incoming wire

### ISSUE THREAD

**Issue by Rezmason** [hundredrabbits/Verreciel#47]
Currently, A -> B prevents C -> B.

For instance, the player can't plug a portal into the pilot until the radar is unplugged from the pilot.

What if routing C to B, first disconnects A from B?

For instance, what if plugging the portal into the pilot disconnects the radar from the pilot?

**Comment by neauoire** [comment]
That's a good idea, I'll implement it that change :)
