### ISSUE TITLE
Account for all music records

### ISSUE THREAD

**Issue by Rezmason** [hundredrabbits/Verreciel#50]
Both wrecks currently offer the same music item. This is easy to fix.

But we should make sure the player can "reach" every music record. Here's my current account for them:

record1: Loiqe (in bank)
record2: Valen (**missing from universe**)
record3: Senni (in _both_ wrecks)
record4: Usul (combine record1 + record2)
record5 (record_oquonie): Pillar (**missing from universe**)

Since record2 is missing from the universe, it's impossible to make record4.

So! If we put record2 in one of the wrecks, that just leaves the Oquonie record.

**Comment by neauoire** [comment]
Ah yes, that was a mistake, I wanted to do:

- valen bank(rec1)
- valen wreck(rec2)
- senni wreck(rec3)
- horadric (any two records -> rec4)
